// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of AppointmentCreate.
  static let AppointmentCreatePayload = ApolloAPI.Object(
    typename: "AppointmentCreatePayload",
    implementedInterfaces: []
  )
}