// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of AttachmentRemove.
  static let AttachmentRemovePayload = ApolloAPI.Object(
    typename: "AttachmentRemovePayload",
    implementedInterfaces: []
  )
}