// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of AttachmentCreate.
  static let AttachmentCreatePayload = ApolloAPI.Object(
    typename: "AttachmentCreatePayload",
    implementedInterfaces: []
  )
}