// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CarePlanAssign.
  static let CarePlanAssignPayload = ApolloAPI.Object(
    typename: "CarePlanAssignPayload",
    implementedInterfaces: []
  )
}