// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of CarePlanCreate.
  static let CarePlanCreatePayload = ApolloAPI.Object(
    typename: "CarePlanCreatePayload",
    implementedInterfaces: []
  )
}