// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of DeviceUnregister.
  static let DeviceUnregisterPayload = ApolloAPI.Object(
    typename: "DeviceUnregisterPayload",
    implementedInterfaces: []
  )
}