// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of TaskCreate.
  static let TaskCreatePayload = ApolloAPI.Object(
    typename: "TaskCreatePayload",
    implementedInterfaces: []
  )
}