// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of TaskIntervalComplete.
  static let TaskIntervalCompletePayload = ApolloAPI.Object(
    typename: "TaskIntervalCompletePayload",
    implementedInterfaces: []
  )
}