// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of TaskComplete.
  static let TaskCompletePayload = ApolloAPI.Object(
    typename: "TaskCompletePayload",
    implementedInterfaces: []
  )
}