// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of TaskRemove.
  static let TaskRemovePayload = ApolloAPI.Object(
    typename: "TaskRemovePayload",
    implementedInterfaces: []
  )
}