// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of TaskActivate.
  static let TaskActivatePayload = ApolloAPI.Object(
    typename: "TaskActivatePayload",
    implementedInterfaces: []
  )
}