// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UserNotificationMarkRead.
  static let UserNotificationMarkReadPayload = ApolloAPI.Object(
    typename: "UserNotificationMarkReadPayload",
    implementedInterfaces: []
  )
}