// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UserCreate.
  static let UserCreatePayload = ApolloAPI.Object(
    typename: "UserCreatePayload",
    implementedInterfaces: []
  )
}