// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UserNotificationCreate.
  static let UserNotificationCreatePayload = ApolloAPI.Object(
    typename: "UserNotificationCreatePayload",
    implementedInterfaces: []
  )
}