// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UserRequestPasswordReset.
  static let UserRequestPasswordResetPayload = ApolloAPI.Object(
    typename: "UserRequestPasswordResetPayload",
    implementedInterfaces: []
  )
}