// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UserUpdate.
  static let UserUpdatePayload = ApolloAPI.Object(
    typename: "UserUpdatePayload",
    implementedInterfaces: []
  )
}