// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of WorkoutRoutineUpdate.
  static let WorkoutRoutineUpdatePayload = ApolloAPI.Object(
    typename: "WorkoutRoutineUpdatePayload",
    implementedInterfaces: []
  )
}